<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <Title>osu!resources</Title>
    <Product>osu!resources</Product>
    <Company>ppy Pty Ltd</Company>
  </PropertyGroup>
  <PropertyGroup Label="Nuget">
    <Title>osu!resources</Title>
    <PackageId>ez2lazer.Game.Resources</PackageId>
    <AssemblyName>osu.Game.Resources</AssemblyName>
    <Authors>ppy Pty Ltd, SK-la</Authors>
    <PackageLicenseUrl>https://github.com/SK-la/osu-resources/blob/master/LICENCE.md</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/SK-la/osu-resources</PackageProjectUrl>
    <RepositoryUrl>https://github.com/SK-la/osu-resources</RepositoryUrl>
    <PackageReleaseNotes>Ez2Lazer redistribution (ez2lazer.Game.Resources). Modified by SK-la.</PackageReleaseNotes>
    <copyright>Original Copyright: Copyright (c) 2026 ppy Pty Ltd. Original code from: https://github.com/ppy/osu-resources. Modified by SK-la.</copyright>
    <PackageTags>osu game resources</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Beatmaps\**\*" />
    <EmbeddedResource Include="Fonts\**\*" />
    <EmbeddedResource Include="Samples\**\*" />
    <EmbeddedResource Include="Skins\**\*" />
    <EmbeddedResource Include="Shaders\**\*" />
    <EmbeddedResource Include="Textures\**\*" />
    <EmbeddedResource Include="Tracks\**\*" />
  </ItemGroup>
  <ItemGroup>
    <!-- Resolves references to LocalisableString. -->
    <PackageReference Include="ppy.osu.Framework" Version="2026.209.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>